### ISSUE TITLE
Citations no longer showing "context"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-bibliography#31]
For example in the IEEE style, this:
```
cite:[iso:27001, clause="6.1.2 c 2"]
```

Will show:
```
[2]
```

It should show something like:
```
[2] (Clause 6.1.2 c 2)
# or
Clause 6.1.2 c 2 of [2]
```

**Comment by paolobrasolin** [comment]
That's actually expected behaviour: the only locators included by the CSL spec are: book, chapter, column, figure, folio, issue, line, note, opus, page, paragraph, part, section, sub-verbo, verse, volume.

This means these are the only ones that we can expect to be rendered by a CSL style (that implements them).

I think that it should be possible to use a generic unqualified locator and let the styles handle it as-is. E.g. `cite:[iso:27001, "Clause 6.1.2 c 2"]` could be rendered as expected. Than might make more sense instead of trying to cover every possible case? (That's what BibTeX&co do.)

Another option would be to use a custom formatter (say, enriching the TeX-like one). But again, if one comes from the TeX world she probably expects to be able to give arbitrary locators.

**Comment by ronaldtse** [comment]
Or maybe just:
```
cite:[iso:27001, prefix="Clause 6.1.2 c 2 of "]
cite:[iso:27001, suffix="Section 3"]
```
?

I can't figure out how to use those locators -- the underlying CSL style needs to support them first, right?

**Comment by paolobrasolin** [comment]
Branch citations implement prefix, suffix, all standard CSL locators and a custom "locator" locator. TeX macros will require a bit more thought.

**Comment by ronaldtse** [comment]
Should we close this due to #39?

**Comment by paolobrasolin** [comment]
Problem is solved for CSL citations but not yet for TeX ones.
However #38 is a better place to discuss that in order to keep things separated. Closing.
