### ISSUE TITLE
Bibliography sorting issue

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-bibliography#32]
This style gives me a sorted bibliography, which is correct:
```
:bibliography-reference-style: din-1505-2-alphanumeric
:bibliography-citation-style: numbers
:bibliography-order: alphabetical
```

Output:
```
[aicpa:tsp100] AICPA, Technical Practice Aids: Trust Services Principles, Criteria and Illustrations (AICPA). New York, USA : American Institute of Certified Public Accountants, Inc., 2014

[cdsa:cps] CDSA: Content Protection & Security Standard and Guidance (CDSA). New York, USA : Content Delivery & Security Alliance, 2014
```

However, this gives me an unsorted one:
```
:bibliography-reference-style: ieee
:bibliography-citation-style: numbers
:bibliography-order: alphabetical
```

Output:
```
[1]CDSA, “Content Protection & Security Standard and Guidance,” Content Delivery & Security Alliance, New York, USA, CDSA, Mar. 2014.

[2]ISO, “Quality management systems—Requirements,” International Organization for Standardization, Geneva, Switzerland, ISO 9001:2015(E), 2015.

[3]ISO, “Environmental management systems—Requirements with guidance for use,” International Organization for Standardization, Geneva, Switzerland, ISO 14001:2015(E), 2015.
```

**Comment by paolobrasolin** [comment]
Ok, I can see why. Let's completely determine the desired behaviour.

The reason why that is happening is that CSL in general can prescribe (separately) complex sorting criteria for both grouped citations and bibliographic indices. (It is now prevailing upon the custom options).

To me, it'd make sense that by default sorting is performed using the criteria given by the CSL style, and that could be overwritten by a custom option that can take some simple values. Say, "author" (by last name of first author), "label" (by citation number, din code, other keys), "appearance" (no sorting at all).

Should we be able to specify more complex sorting behaviour? (e.g. lists of sorting keys)
Do any other criteria come to mind?

**Comment by ronaldtse** [comment]
@paolobrasolin agree that we should fully specify the behavior.

These should be good enough?
* author (last name of first (author or editor))
* label ([1] or [aicpa], etc)
* appearance (order of appearance in document)
* title
* date (year / month / day)
* publisher
* institution
* shorthand ?
* type

**Comment by paolobrasolin** [comment]
I had an idea; I wrote a stub for a general sorting mechanism in the branch `sorting`. You can find a sample use in the `standard/sample-deafult.adoc` sample.

Here is my reasoning. If we implement custom-named sorting styles, we must also make assumptions about how the CSL styles are structured: while the *variables* are defined by the CSL spec, what we're really interested in is *macros*. Those define how pieces of info are rendered and therefore they also are the most relevant for sorting. While their naming is  usually pretty reasonable, it's also completely arbitrary. This means that when someone is using a style that has macros named with a different convention than our assumptions, the sorting can and will break. What's worst is that the user has no way to fix that except writing custom code.

If we make *no* assumptions instead, I think we have an alternative solution. The idea is to let the user specify the sorting keys with a short YAML string. Here are some examples:

```
:bibliography-sort: macro: author
:bibliography-sort: { macro: author, sort: descending }
:bibliography-sort: [{ macro: author, sort: descending }, { variable: title, sort: ascending}]
```

While this is a bit more verbose, we have multiple advantages:

- no magic hardcoded stuff
- much simpler implementation
- user has full control: both keys and variables, explicitly stated, single or multiple sorting keys, all CSL options are available (only the trivial ones are shown above)

Since variables and macros usually have reasonable names this does not necessarily require knowledge of the CSL style itself. And if the user is trying to override the sorting specified by the style, she's probably savvy enough to recover the macro names from the Visual CSL Editor (we should write a note about that in the manual).

It seems to me that the advantages greatly outweight the flaws of this approach.
What do you think? @ronaldtse

**Comment by ronaldtse** [comment]
This is indeed a really good idea. The less magic we do the more predicatable the behavior. 

Let's go for it. Thanks!

**Comment by paolobrasolin** [comment]
Implemented and documented in branch sort-option.

**Comment by ronaldtse** [comment]
Ready to close as #35 is merged?

**Comment by paolobrasolin** [comment]
Ready. Closing.
