### ISSUE TITLE
Segregating normative and informative bibliography

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-bibliography#55]
I strongly recommend that the differentiation between normative and informative bibliography items occur through attributes of the bibtex item: e.g. possibly

````
@misc{RFC3536,
bibliography="informative",
}
````

or

````
@misc{RFC3536,
bibliography="normative",
}
````

Once that is done, instead of having a single macro instance `bibliography::[]`, we would have two instances, one for each type of bibliography:

````
[bibliography]
== References

[bibliography]
=== Normative References
bibliography::[normative]

=== Informative References
bibliography::[informative]
````

**Comment by ronaldtse** [comment]
I agree with @opoudjis that we have a strong need to separate bibliography groups. However I don't think BibTeX is the right place to do it because it corrupts the BibTeX file -- the BibTeX file is simply the database for ALL bibliography items and is often just a huge collection that is shared between multiple documents (sorry I do that a lot).

On the other hand, the MMark concept of "upgrading" bibliography item types from "informative" to "normative" does not resonate with me because the groups are simply "different".

How about we consider something like this?
```
cite:[rfc1234,group="group1"]
cite:[rfc2345,group="group2"]

[bibliography]
=== Group 1 References
bibliography::[group1]

=== Group 2 References
bibliography::[group2]
```

**Comment by blablatros** [comment]
I agree that grouping should be done in the document, not the bibtex file.

We should also consider the possibility that one bibliography item can belong to two or more groups.

**Comment by ronaldtse** [comment]
Indeed, and the decision whether a bibliography item should belong to multiple groups should be decided by the “citer”.

**Comment by paolobrasolin** [comment]
I agree with @ronaldtse and @blablatros in thinking that DB data should be agnostic with respect to groupings. Groups are in essence "roles" and will almost surely depend upon the specific use the citer makes of the entries.

I gave some thought to groupings when writing the macro parser and laid some simple groundwork.
What I had in mind was using the *target* syntax for asciidoctor macros. I.e.:
```
cite:group1[rfc1234]
cite:group2[rfc2345]

[bibliography]
=== Group 1 References
bibliography::group1[]

=== Group 2 References
bibliography::group2[]
```

How does that look?

**Comment by ronaldtse** [comment]
@paolobrasolin the syntax looks great to me! If there is no `group` given we can keep the reference in the "default" reference group.

**Comment by opoudjis** [comment]
That works. The abbreviations "norm" and "info" are going to be more user-friendly, and we can assume them for asciidoctor-rfc.

**Comment by blablatros** [comment]
It is better to let the users choose group names.

For example, social sciences, especially history, often groups references into "primary" and "secondary".

**Comment by ronaldtse** [comment]
@blablatros indeed we should allow users to choose group names.

I think @opoudjis just means that in the `asciidoctor-rfc` gem we could have some special syntax to use those bibliography groups, because those are specific requirements of an RFC. Or perhaps we don't even need to specify those specific groups at all since the syntax above is quite clean and simple?
